# Site settings
title: Alex R. Mayfield
description: "Pentecostalism. World Christianity. Digital Methods."
baseurl: "https://alex-mayfield.github.io" # the subpath of your site, e.g. /blog
encoding: UTF-8
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex R. Mayfield
user_description: Alex Mayfield is a Associate Professor of Historical Theology & Global Christianity at Oral Roberts University. His research utilizes digital methodologies to reconstruct historical networks and movements within global Christianity. His current research and teaching interests include pentecostal and charismatic movements, mission history in East Asia, and the intersection of religion and technology.
user_title: "Pentecostalism. World Christianity. Digital Methods."
email: almayfield@oru.edu
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

sass:
    sass_dir: src/styles
    style: compressed

exclude:
  - package.json
  #- src
  - node_modules
