# Site settings
title: Alex R. Mayfield
description: Global Church Historian and Pentecostal Scholar
baseurl: "https://alex-mayfield.github.io" # the subpath of your site, e.g. /blog
encoding: UTF-8
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex R. Mayfield
user_description: I help students understand the complex, rich, and interconnected history of global Christianity. Working in historical and digital methodologies, my research interests include global Pentecostal and Charismatic movements, ecumenism, mission history in Asia, and the development of Chinese Christianity in the modern period.
user_title: Global Church Historian and Pentecostal Scholar
email: mayfieaa@bu.edu
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

sass:
    sass_dir: src/styles
    style: compressed

exclude:
  - package.json
  #- src
  - node_modules
