# Site settings
title: Alex R. Mayfield
description: Jekyll Theme Minimal Resume
baseurl: "https://alex-mayfield.github.io" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex Mayfield
user_description: I help students understand the complex, rich, and interconnected history of global Christianity and the pentecostal movement.
user_title: Global Church Historian and Pentecostal Scholar
email: mayfieaa@bu.edu
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
