list:
  - title: "Associate Editor, Pneuma: The Journal of the Society for Pentecostal Studies"
    year: 2023-2024
  - title: "Managing Editor, Pneuma: The Journal of the Society for Pentecostal Studies"
    year: 2020-2022
  - title: "Student Director, New England-Maritimes Region of the American Academy of Religion"
    year: 2018-2020
  - title: Representative of the International Pentecostal Holiness Church, Evangelical-Catholic Dialogue of the United States
    year: Since 2017
  - title: Licensed Minister, International Pentecostal Holiness Church.
    year: Since 2014
