list:
  - title: "Managing Editor, Pneuma: The Journal of the Society for Pentecostal Studies"
    year: Since 2020
  - title: "Student Director, New England-Maritimes Region of the American Academy of Religion"
    year: 2018-2020
