list:
  - title: "Associate Editor, Pneuma: The Journal of the Society for Pentecostal Studies"
    year: 2023-2024
  - title: "Managing Editor, Pneuma: The Journal of the Society for Pentecostal Studies"
    year: 2020-2022
  - title: "Student Director, New England-Maritimes Region of the American Academy of Religion"
    year: 2018-2020
